//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringBasedCommunicationFacilitator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringBasedCommunicationFacilitator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully completed.
        /// </summary>
        internal static string ERR_000 {
            get {
                return ResourceManager.GetString("ERR_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web service generic error.
        /// </summary>
        internal static string ERR_500 {
            get {
                return ResourceManager.GetString("ERR_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong username/password.
        /// </summary>
        internal static string ERR_550 {
            get {
                return ResourceManager.GetString("ERR_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not authorized to call this message.
        /// </summary>
        internal static string ERR_552 {
            get {
                return ResourceManager.GetString("ERR_552", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input string is too long.
        /// </summary>
        internal static string ERR_554 {
            get {
                return ResourceManager.GetString("ERR_554", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string to split is null.
        /// </summary>
        internal static string ERR_555 {
            get {
                return ResourceManager.GetString("ERR_555", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chunk length is not valid.
        /// </summary>
        internal static string ERR_556 {
            get {
                return ResourceManager.GetString("ERR_556", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this nullable type is not supported.
        /// </summary>
        internal static string ERR_561 {
            get {
                return ResourceManager.GetString("ERR_561", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type is not supported.
        /// </summary>
        internal static string ERR_562 {
            get {
                return ResourceManager.GetString("ERR_562", resourceCulture);
            }
        }
    }
}
